version: "1"
services:
  - type: web
    name: sparkonomy-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        value: file:/tmp/dev.db
      - key: CORS_ORIGINS
        value: https://sparkonomy-frontend.onrender.com

  - type: web
    name: sparkonomy-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://sparkonomy-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
